version: 0.1

phases:
  install:
    commands:
      - echo "Updating AWS CLI..."
      - pip install --upgrade awscli

      - echo "Installing Mustache Globally"
      - npm install -g mustache

      - echo "Installing Project Dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Creating AWS Config file"
      - node -e 'console.log(JSON.stringify(process.env))' > build.json

  build:
    commands:
      # - echo "Running lint..."
      # - npm run lint

      # - echo "Running tests..."
      # - npm run test

      - echo "Packaging Client & Server..."
      - npm run build

      - echo "Compiling API template..."
      - mustache build.json api.yml > out/api.yml

      - echo "Compiling Cloudformation (Bucket $S3_BUCKET)..."
      - "aws cloudformation package --template-file service.yml --s3-prefix build --s3-bucket $S3_BUCKET --output-template-file template.yml"

artifacts:
  type: zip
  discard-paths: no
  files:
    # - artifacts/**/*
    - out/**/*
    - template.yml
    - build.json
    - assets.yml
    - assetspec.yml
